import React from 'react';
import { ArrowRight } from 'lucide-react';

export default function HomeView({ 
  englishInput, 
  setEnglishInput, 
  aiModel, 
  setAiModel, 
  activeSchema, 
  onGenerate, 
  loading 
}) {
  
  // Try Examples grouped by active schema
  const tryExamples = {
    college: [
      { text: "Students in Computer Science", label: "CS Students" },
      { text: "Show top 5 students by CGPA", label: "Top CGPA" },
      { text: "Courses taught in Computer Science", label: "CS Courses" }
    ],
    ecommerce: [
      { text: "Top 5 customers by sales", label: "Top Customers" },
      { text: "Products with low stock", label: "Low Inventory" },
      { text: "Total revenue from orders", label: "Total Revenue" }
    ],
    hospital: [
      { text: "Patients older than 40", label: "Older Patients" },
      { text: "Appointments scheduled for today", label: "Today's Schedule" },
      { text: "Patients diagnosed with Migraine", label: "Migraine Patients" }
    ],
    business: [
      { text: "Employees in Sales department", label: "Sales Staff" },
      { text: "Total revenue generated by sales", label: "Sales Revenue" },
      { text: "Sales ordered by highest revenue", label: "Sort Sales" }
    ]
  };

  const currentChips = tryExamples[activeSchema] || tryExamples.college;

  const handleChipClick = (text) => {
    setEnglishInput(text);
    onGenerate(text);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
      
      {/* Console Area - Left */}
      <div className="lg:col-span-8 space-y-6">
        {/* Intro */}
        <div className="space-y-3">
          <h2 className="font-outfit font-extrabold text-3xl md:text-4xl text-text-primary tracking-tight leading-tight">
            Ask Anything, <span className="bg-clip-text text-transparent bg-gradient-to-r from-brand-purple to-brand-cyan">Get SQL Instantly</span>
          </h2>
          <p className="text-text-secondary max-w-xl text-sm md:text-base leading-relaxed">
            Enter your question in plain English and let Gemini AI do the magic. Generate structured, optimized SQL scripts tailored to your database in seconds.
          </p>
        </div>

        {/* Input Card */}
        <div className="glass-panel rounded-2xl p-6 shadow-lg space-y-5 transition-all duration-300">
          
          {/* Header config */}
          <div className="flex items-center justify-between pb-3 border-b border-border-card">
            <span className="font-outfit font-semibold text-text-primary text-sm">Describe what data you need...</span>
            <div className="flex items-center gap-2">
              <span className="text-xs text-text-muted">Model:</span>
              <select 
                value={aiModel} 
                onChange={(e) => setAiModel(e.target.value)}
                className="bg-bg-primary border border-border-card text-text-primary rounded-lg px-2 py-1 text-xs outline-none focus:border-brand-purple transition-all duration-200"
              >
                <option value="gpt4">GPT-4 Turbo</option>
                <option value="gemini">Gemini 1.5 Flash</option>
                <option value="claude">Claude 3.5 Sonnet</option>
              </select>
            </div>
          </div>

          {/* Prompt Input */}
          <div>
            <textarea
              value={englishInput}
              onChange={(e) => setEnglishInput(e.target.value)}
              placeholder="Example: Show all students who scored more than 8.5 in exams..."
              className="w-full h-36 bg-bg-card text-text-primary placeholder-text-muted border border-border-card rounded-xl p-4 text-sm font-mono focus:border-brand-purple focus:ring-1 focus:ring-brand-purple outline-none resize-none transition-all duration-200 caret-text-primary selection:bg-brand-purple/30 selection:text-text-primary"
            />
          </div>

          {/* Chips */}
          <div className="space-y-2.5">
            <span className="text-xs font-semibold text-text-muted block">Try Examples:</span>
            <div className="flex flex-wrap gap-2">
              {currentChips.map((chip, idx) => (
                <button
                  key={idx}
                  onClick={() => handleChipClick(chip.text)}
                  className="bg-bg-primary border border-border-card text-text-secondary hover:text-brand-purple hover:border-brand-purple px-3.5 py-1.5 rounded-full text-xs font-medium transition-all duration-200"
                >
                  {chip.label}
                </button>
              ))}
            </div>
          </div>

          {/* Button */}
          <button
            onClick={() => onGenerate(englishInput)}
            disabled={loading || !englishInput.trim()}
            className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-brand-purple to-brand-blue hover:shadow-glow text-white font-semibold py-3.5 rounded-xl transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed text-sm"
          >
            {loading ? (
              <>
                <span>Translating...</span>
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              </>
            ) : (
              <>
                <span>Generate SQL</span>
                <ArrowRight size={16} />
              </>
            )}
          </button>

        </div>
      </div>

      {/* Mascot & Info - Right */}
      <div className="lg:col-span-4 space-y-6">
        {/* SQL Bot Mascot Card */}
        <div className="glass-panel rounded-2xl p-6 text-center shadow-lg space-y-4">
          <div className="flex justify-center">
            <svg className="w-36 h-36 animate-float" viewBox="0 0 200 200" fill="none" xmlns="http://www.w3.org/2000/svg">
              <circle cx="100" cy="100" r="90" fill="url(#circleGlow)" opacity="0.15"/>
              <rect x="50" y="60" width="100" height="80" rx="20" fill="url(#mascotGrad)" stroke="#8b5cf6" stroke-width="3"/>
              <rect x="38" y="85" width="12" height="30" rx="6" fill="#8b5cf6"/>
              <rect x="150" y="85" width="12" height="30" rx="6" fill="#8b5cf6"/>
              <rect x="96" y="30" width="8" height="30" rx="4" fill="#3b82f6"/>
              <circle cx="100" cy="24" r="10" fill="#06b6d4" className="pulse-glow"/>
              <rect x="62" y="76" width="76" height="30" rx="8" fill="#05070d"/>
              <circle cx="80" cy="91" r="6" fill="#22d3ee"/>
              <circle cx="120" cy="91" r="6" fill="#22d3ee"/>
              <path d="M85 120H115" stroke="#a78bfa" stroke-width="4" stroke-linecap="round"/>
              <rect x="85" y="140" width="30" height="20" rx="5" fill="#3b82f6" opacity="0.7"/>
              <defs>
                <radialGradient id="circleGlow" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" transform="translate(100 100) rotate(90) scale(90)">
                  <stop stopColor="#8b5cf6"/>
                  <stop offset="1" stopColor="#070a13" stopOpacity="0"/>
                </radialGradient>
                <linearGradient id="mascotGrad" x1="50" y1="60" x2="150" y2="140" gradientUnits="userSpaceOnUse">
                  <stop stopColor="#1e1b4b"/>
                  <stop offset="1" stopColor="#0f172a"/>
                </linearGradient>
              </defs>
            </svg>
          </div>
          <h3 className="font-outfit font-bold text-lg text-text-primary">Meet SQL-Bot</h3>
          <p className="text-xs text-text-secondary leading-relaxed">
            Select a schema context, describe what data you want in plain English, and watch me formulate fully optimized queries instantly!
          </p>
        </div>

        {/* Key Features List */}
        <div className="glass-panel rounded-2xl p-6 shadow-lg space-y-4">
          <span className="font-outfit font-bold text-sm text-text-primary block border-b border-border-card pb-2.5">Key Features</span>
          <ul className="space-y-3.5 text-xs text-text-secondary">
            {[
              "Plain English to SQL Conversion",
              "Multiple Use Case Database Schemas",
              "AI Query Explanation & Optimization Advice",
              "Copy, Download, & Execute SQL Instantly",
              "Full-Stack Python & SQLite Execution Playground"
            ].map((feature, i) => (
              <li key={i} className="flex items-center gap-3">
                <div className="w-5 h-5 rounded-full bg-brand-green/10 text-brand-green flex items-center justify-center font-bold text-xs flex-shrink-0">
                  ✓
                </div>
                <span>{feature}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

    </div>
  );
}
